# Generated by Django 3.2.3 on 2021-06-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210606_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('idPeticion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Peticion')),
                ('correo', models.CharField(max_length=60, verbose_name='correo')),
                ('descripcion', models.CharField(max_length=600, verbose_name='descripcion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
