# Generated by Django 3.2.3 on 2021-06-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ilustracionilu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilustracionilu',
            name='imagen',
            field=models.ImageField(null=True, upload_to='ilustraciones', verbose_name='imagen uwu'),
        ),
    ]
