# Generated by Django 3.2.3 on 2021-06-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ilustracionilu_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilustracionilu',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media', verbose_name='imagen'),
        ),
    ]
