# Generated by Django 3.2.3 on 2021-07-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_ilustracionilu_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilustracionilu',
            name='imagen',
            field=models.ImageField(default='core/no-hay-imagen.jpg', upload_to='core', verbose_name='imagen'),
        ),
    ]
